/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shrs.ui;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import shrs.db.DBManager;

/**
 *
 * @author osraldo
 */
public class JfrmMain extends javax.swing.JFrame implements JICustomDialogEvents {
    private String m_sUserAccessLevel;
    /**
     * Creates new form JfrmMain
     */
    public JfrmMain() {
        initComponents();
        jmnStudent.setMnemonic(KeyEvent.VK_S);
        jmnAdministration.setMnemonic(KeyEvent.VK_A);
        jmnJuniorHigh.setMnemonic(KeyEvent.VK_J);
        jmiStudentRegistration.setMnemonic(KeyEvent.VK_R);
        jmiEnrollment.setMnemonic(KeyEvent.VK_E);
        jmiPrintEnrollment.setMnemonic(KeyEvent.VK_P);
        jmnUsers.setMnemonic(KeyEvent.VK_U);
        jmiLogin.setMnemonic(KeyEvent.VK_L);
        jmiLogout.setMnemonic(KeyEvent.VK_O);
        jmiChangePassword.setMnemonic(KeyEvent.VK_C);
        jmiSearchStudent.setMnemonic(KeyEvent.VK_S);
    }
    
    @Override
    public void setDialogSuccess(String sUsername) {
        jmiLogin.setEnabled(false);
        jmiLogout.setEnabled(true);
        jmiChangePassword.setEnabled(true);
        grantAccessToUser(sUsername);
    }
    
    @Override
    public void setDialogSuccess(String sData1, String sData2, String sData3) {
        //Intentionally Void
    }
    
    private void grantAccessToUser(String sUsername) {
        DBManager dbm = new DBManager();
        ResultSet rsTM  = null;
        int nRowCnt = 0;
        String sTbl = "access_grant ag join system_users su on ag.ag_access_level = su.su_access_level";
        String sCols = "ag.ag_access_level, ag.ag_menu_item";
        String sCond = "su.su_username = '" + sUsername + "'";
        try {
            rsTM = dbm.getResultSet(sTbl, sCols, sCond, "");
            //rsTM.last();
            //nRowCnt = rsTM.getRow();
            //rsTM.beforeFirst();
            //if (nRowCnt > 0) {
                while(rsTM.next()) {
                    switch(rsTM.getString("ag_menu_item")) {
                        case "jmiSearchStudent":
                            jmiSearchStudent.setEnabled(true);
                            break;
                        case "jmiConfiguration":
                            jmiConfiguration.setEnabled(true);
                            break;
                        case "jmiAdministerUsers":
                            jmiAdministerUsers.setEnabled(true);
                            break;
                    }
                    m_sUserAccessLevel = rsTM.getString("ag_access_level");
                }
            //}
        } 
        catch(SQLException ex) {
            System.out.println("SQLException: " + ex.getMessage());
        }
        finally	{
            if (rsTM != null) {
                try {
                    rsTM.close();
                } 
                catch(SQLException sqlEx){}//ignore
                rsTM = null;
            }
        }        
    }
    
    private void setMenuDefaults() {
        jmiSearchStudent.setEnabled(false);
        jmiConfiguration.setEnabled(false);
        jmiAdministerUsers.setEnabled(false);
        jmiChangePassword.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jmbMain = new javax.swing.JMenuBar();
        jmnStudent = new javax.swing.JMenu();
        jmiStudentRegistration = new javax.swing.JMenuItem();
        jmiEnrollment = new javax.swing.JMenuItem();
        jmiPrintEnrollment = new javax.swing.JMenuItem();
        jmnAdministration = new javax.swing.JMenu();
        jmnUsers = new javax.swing.JMenu();
        jmiLogin = new javax.swing.JMenuItem();
        jmiLogout = new javax.swing.JMenuItem();
        jmiChangePassword = new javax.swing.JMenuItem();
        jmiAdministerUsers = new javax.swing.JMenuItem();
        jmnMaintenance = new javax.swing.JMenu();
        jmiConfiguration = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiSearchStudent = new javax.swing.JMenuItem();
        jmnJuniorHigh = new javax.swing.JMenu();
        jmiJuniorHighRegistration = new javax.swing.JMenuItem();
        jmiJuniorHighPrintRegistration = new javax.swing.JMenuItem();
        jmnHelp = new javax.swing.JMenu();
        jmiAbout = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MHS - SHARES");

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shrs/resources/SHARES_Logo.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shrs/resources/PoweredBy.png"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel2, java.awt.BorderLayout.PAGE_END);

        jmnStudent.setText("Student");

        jmiStudentRegistration.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jmiStudentRegistration.setText("Student Registration");
        jmiStudentRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiStudentRegistrationActionPerformed(evt);
            }
        });
        jmnStudent.add(jmiStudentRegistration);

        jmiEnrollment.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jmiEnrollment.setText("Enrollment");
        jmiEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEnrollmentActionPerformed(evt);
            }
        });
        jmnStudent.add(jmiEnrollment);

        jmiPrintEnrollment.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jmiPrintEnrollment.setText("Print Enrollment");
        jmiPrintEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrintEnrollmentActionPerformed(evt);
            }
        });
        jmnStudent.add(jmiPrintEnrollment);

        jmbMain.add(jmnStudent);

        jmnAdministration.setText("Administration");

        jmnUsers.setText("Users");

        jmiLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jmiLogin.setText("Login");
        jmiLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLoginActionPerformed(evt);
            }
        });
        jmnUsers.add(jmiLogin);

        jmiLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jmiLogout.setText("Logout");
        jmiLogout.setEnabled(false);
        jmiLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLogoutActionPerformed(evt);
            }
        });
        jmnUsers.add(jmiLogout);

        jmiChangePassword.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jmiChangePassword.setText("Change Password");
        jmiChangePassword.setEnabled(false);
        jmiChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiChangePasswordActionPerformed(evt);
            }
        });
        jmnUsers.add(jmiChangePassword);

        jmiAdministerUsers.setText("Administer Users");
        jmiAdministerUsers.setEnabled(false);
        jmiAdministerUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAdministerUsersActionPerformed(evt);
            }
        });
        jmnUsers.add(jmiAdministerUsers);

        jmnAdministration.add(jmnUsers);

        jmnMaintenance.setText("Maintenance");

        jmiConfiguration.setText("Configuration");
        jmiConfiguration.setEnabled(false);
        jmiConfiguration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConfigurationActionPerformed(evt);
            }
        });
        jmnMaintenance.add(jmiConfiguration);

        jmnAdministration.add(jmnMaintenance);
        jmnAdministration.add(jSeparator1);

        jmiSearchStudent.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jmiSearchStudent.setText("Search Student");
        jmiSearchStudent.setEnabled(false);
        jmiSearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSearchStudentActionPerformed(evt);
            }
        });
        jmnAdministration.add(jmiSearchStudent);

        jmbMain.add(jmnAdministration);

        jmnJuniorHigh.setText("Junior High School");

        jmiJuniorHighRegistration.setText("Registration");
        jmiJuniorHighRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiJuniorHighRegistrationActionPerformed(evt);
            }
        });
        jmnJuniorHigh.add(jmiJuniorHighRegistration);

        jmiJuniorHighPrintRegistration.setText("Print Registration");
        jmiJuniorHighPrintRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiJuniorHighPrintRegistrationActionPerformed(evt);
            }
        });
        jmnJuniorHigh.add(jmiJuniorHighPrintRegistration);

        jmbMain.add(jmnJuniorHigh);

        jmnHelp.setText("Help");

        jmiAbout.setText("About");
        jmiAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAboutActionPerformed(evt);
            }
        });
        jmnHelp.add(jmiAbout);

        jmbMain.add(jmnHelp);

        setJMenuBar(jmbMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiStudentRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiStudentRegistrationActionPerformed
        JdlgRegStudentNew dlg = new JdlgRegStudentNew(this, true);
        dlg.setVisible(true);
    }//GEN-LAST:event_jmiStudentRegistrationActionPerformed

    private void jmiLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLoginActionPerformed
        JLogin dlg = new JLogin(this, this, true);
        dlg.setVisible(true);
    }//GEN-LAST:event_jmiLoginActionPerformed

    private void jmiChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiChangePasswordActionPerformed
        JChangePassword dlg = new JChangePassword(this, true);
        dlg.setVisible(true);
    }//GEN-LAST:event_jmiChangePasswordActionPerformed

    private void jmiAdministerUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAdministerUsersActionPerformed
        JUserMaintenance dlg = new JUserMaintenance(this, true);
        dlg.setVisible(true);
    }//GEN-LAST:event_jmiAdministerUsersActionPerformed

    private void jmiAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAboutActionPerformed
 
    }//GEN-LAST:event_jmiAboutActionPerformed

    private void jmiSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSearchStudentActionPerformed
        JSearchStudent dlg = new JSearchStudent(this, false, m_sUserAccessLevel);
        dlg.setVisible(true);
    }//GEN-LAST:event_jmiSearchStudentActionPerformed

    private void jmiLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLogoutActionPerformed
        jmiLogin.setEnabled(true);
        jmiLogout.setEnabled(false);
        setMenuDefaults();
        m_sUserAccessLevel = null;
    }//GEN-LAST:event_jmiLogoutActionPerformed

    private void jmiEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEnrollmentActionPerformed
        JEnrollStudent dlg = new JEnrollStudent(this, true);
        dlg.setVisible(true);
    }//GEN-LAST:event_jmiEnrollmentActionPerformed

    private void jmiPrintEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrintEnrollmentActionPerformed
        JPrintStudentForm dlg = new JPrintStudentForm(this, false);
        dlg.setVisible(true);
    }//GEN-LAST:event_jmiPrintEnrollmentActionPerformed

    private void jmiConfigurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConfigurationActionPerformed
        JConfiguration dlg = new JConfiguration(this, true);
        dlg.setVisible(true);
    }//GEN-LAST:event_jmiConfigurationActionPerformed

    private void jmiJuniorHighRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiJuniorHighRegistrationActionPerformed
        JJuniorHighReg dlg = new JJuniorHighReg(this, true);
        dlg.setVisible(true);
    }//GEN-LAST:event_jmiJuniorHighRegistrationActionPerformed

    private void jmiJuniorHighPrintRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiJuniorHighPrintRegistrationActionPerformed
        JJuniorHighRegPrint dlg = new JJuniorHighRegPrint(this, false);
        dlg.setVisible(true);
    }//GEN-LAST:event_jmiJuniorHighPrintRegistrationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar jmbMain;
    private javax.swing.JMenuItem jmiAbout;
    private javax.swing.JMenuItem jmiAdministerUsers;
    private javax.swing.JMenuItem jmiChangePassword;
    private javax.swing.JMenuItem jmiConfiguration;
    private javax.swing.JMenuItem jmiEnrollment;
    private javax.swing.JMenuItem jmiJuniorHighPrintRegistration;
    private javax.swing.JMenuItem jmiJuniorHighRegistration;
    private javax.swing.JMenuItem jmiLogin;
    private javax.swing.JMenuItem jmiLogout;
    private javax.swing.JMenuItem jmiPrintEnrollment;
    private javax.swing.JMenuItem jmiSearchStudent;
    private javax.swing.JMenuItem jmiStudentRegistration;
    private javax.swing.JMenu jmnAdministration;
    private javax.swing.JMenu jmnHelp;
    private javax.swing.JMenu jmnJuniorHigh;
    private javax.swing.JMenu jmnMaintenance;
    private javax.swing.JMenu jmnStudent;
    private javax.swing.JMenu jmnUsers;
    // End of variables declaration//GEN-END:variables
}
