/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shrs.ui;

import java.security.NoSuchAlgorithmException;
import java.sql.Types;
import javax.swing.JOptionPane;
import shrs.db.DBManager;
import shrs.db.SPParam;
import shrs.db.TypeParam;
import shrs.utility.HashCode;
import java.awt.event.KeyEvent;

/**
 *
 * @author osraldo
 */
public class JLogin extends javax.swing.JDialog {
    JICustomDialogEvents iparentFrm = null;
    /**
     * Creates new form JLogin
     */
    public JLogin(java.awt.Frame parent, JICustomDialogEvents iparent, boolean modal) {
        super(parent, "Login to use other features.", modal);
        initComponents();
        iparentFrm = iparent;
        setLocationRelativeTo(parent);
    }
    
    private SPParam[] LoginSystemUserPassword() {
        SPParam[] arrParams = new SPParam[4];
        arrParams[0] = new SPParam<String>(Types.VARCHAR, TypeParam.In, 1, "psu_username", 
            jtxfUsername.getText());
        String sPassword = new String(jpwfPassword.getPassword());
        try{sPassword = HashCode.md5(sPassword);}catch(NoSuchAlgorithmException nex){}
        arrParams[1] = new SPParam<String>(Types.VARCHAR, TypeParam.In, 2, "psu_password", 
            sPassword);

        arrParams[2] = new SPParam<Integer>(Types.INTEGER, TypeParam.Out, 3, "psu_flag", 0);
        arrParams[3] = new SPParam<String>(Types.VARCHAR, TypeParam.Out, 4, "psu_error_desc", "");

        DBManager dbm = new DBManager();
        return dbm.executeStoredProc("SP_SystemUserLogin", arrParams);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jtxfUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jpwfPassword = new javax.swing.JPasswordField();
        jbtnCancel = new javax.swing.JButton();
        jbtnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel2.setText("Username:");

        jLabel1.setText("Password:");

        jbtnCancel.setMnemonic(KeyEvent.VK_C);
        jbtnCancel.setText("Cancel");
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });

        jbtnLogin.setMnemonic(KeyEvent.VK_L);
        jbtnLogin.setText("Login");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpwfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnCancel)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtnCancel, jbtnLogin});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jpwfPassword, jtxfUsername});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jpwfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCancel)
                    .addComponent(jbtnLogin))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        SPParam[] outParams = LoginSystemUserPassword();
        if (outParams != null) {
            Integer nOut = new Integer(outParams[0].getParamValue().toString());
            if(nOut != 0) {
                String sErrMsg =  outParams[1].getParamValue().toString();
                JOptionPane.showMessageDialog(this, sErrMsg, this.getTitle(), JOptionPane.ERROR_MESSAGE);
            }
            else {
                iparentFrm.setDialogSuccess(jtxfUsername.getText());
                String sMsg =  outParams[1].getParamValue().toString();
                JOptionPane.showMessageDialog(this, sMsg,
                this.getTitle(), JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "An error occured. Please contact your system admin.",
            this.getTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnLoginActionPerformed

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JPasswordField jpwfPassword;
    private javax.swing.JTextField jtxfUsername;
    // End of variables declaration//GEN-END:variables
}
